name: 'rick_and_morty'

version: '1.0.0'

config-version: 2


profile: 'rick_and_morty'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  rick_and_morty:
    staging:
      +materialized: table
      +schema: STAGING