# print("ID:", data["id"])
# print("Название:", data["name"])
# print("Тип:", data["type"])
# print("Измерение:", data["dimension"])
# residents = []
# for j in data["residents"]:
#     parts = j.split("/")
#     residents.append(int(parts[-1]))
# print("Жители:", residents)
# # print("URL:", data["url"])
# print("Создан:", data["created"])

#     print("ID:", data["id"])
            #     print("Название:", data["name"])
            #     print("Дата выхода:", data["air_date"])
            #     print("Код эпизода:", data["episode"])
            #     characters = []
            #     for j in data["characters"]:
            #         parts = j.split("/")
            #         characters.append(int(parts[-1]))
            #     print("Персонажи:", characters)
            #     # print("URL:", data["url"])
            #     print("Создан:", data["created"])

# print("ID:", data["id"])
# print("Имя:", data["name"])
# print("Статус:", data["status"])
# print("Вид:", data["species"])
# print("Тип:", data["type"])
# print("Пол:", data["gender"])
# print("Происхождение:", data["origin"]["name"])
# print("Локация:", data["location"]["name"])
# print("Картинка:", data["image"])
# print("Кол-во эпизодов:", len(data["episode"]))
# # print("URL:", data["url"])
# print("Создан:", data["created"])
#
# ch["id"].append(is_empty(data["id"]))
# ch["name"].append(is_empty(data["name"]))
# ch["status"].append(is_empty(data["status"]))
# ch["species"].append(is_empty(data["species"]))
# ch["type"].append(is_empty(data["type"]))
# ch["gender"].append(is_empty(data["gender"]))
# ch["origin"].append(is_empty(data["origin"]["name"]))
# ch["location"].append(is_empty(data["location"]["name"]))
# ch["image"].append(is_empty(data["image"]))
# ch["created"].append(is_empty(data["created"]))